version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins_ansible_master
    network_mode: "host"
    # Make absolutely sure the 'ports:' section below is DELETED or COMMENTED OUT
    # ports:
    #   - "8080:8080"
    #   - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always

volumes:
  jenkins_home: